### ISSUE TITLE
Add a searchbar for ingredients

### ISSUE THREAD

**Issue by KarinLiegmann** [KarinLiegmann/capstone-project#2]

**Comment by KarinLiegmann** [comment]
_As an app user I want to search for an ingredient so that I can add it to a list of ingredients that I have at home._

**Acceptance Criteria**
- [ ] Click on the searchbar gives the option to type in an ingredient
- [ ] The search-query must have at least 2 characters
- [ ] The search-query must be a string and can not start with a number
- [ ] The search-query ignores uppercase- or lowercase-writing
- [ ] While typing, you get autofill-recommendations of ingredients
- [ ] You can not add ingredients with any other button than 'Enter'
- [ ] Pressing 'Enter' adds the ingredient to the ingredient list
- [ ] There must be at least 2 ingredients in the list to start a search

**Tasks**
- [ ] New feature-branch 'search-bar'
- [ ] Add 'search-bar'-component
- [ ] Create a text-inputfield as seachbar
- [ ] Convert the value of the input-field to lowercase-characters
- [ ] Show an error-message when trying to start the search-query with datatype Number
- [ ] Show error-message when the value is less than 2 characters
- [ ] Implement search-logic (connect to API)
- [ ] Show Error Message and deactivate the Button for 'Find recipes' when there are less than 2 ingredients in the list
- [ ] Add test
- [ ] Add prop-types to seach-bar
- [ ] Add styleguidist-documentation for search-bar

**Complexity: L**
