### ISSUE TITLE
Add ingredients tags

### ISSUE THREAD

**Issue by KarinLiegmann** [KarinLiegmann/capstone-project#3]
**Description**
_As an app user I want to add an ingredient to the list of ingredients I have so I can use it to search for recipes with this ingredient._

**Acceptance Criteria**
- [x] Pressing 'Enter' on the searchbar adds an ingredient as tag to my ingredients list
- [x] The ingredient I added last will be at the top of my list

**Tasks**
- [x] New feature-branch 'ingredient-tags'
- [x] Add 'ingredient-tag'-component
- [x] Add ingredient to localStorage
- [x] Push ingredient into an array of ingredients?
- [x] Render ingredient as a tag
